service: beast

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-webpack

functions:
  takeScreenshot:
    handler: takeScreenshot.default
